Repository netboxlabs/diode-netbox-plugin, pull requests merged in 2024-09, with the labels that each got.

#21 feat: NetBox 4.1 support
  README.md
  docker/Dockerfile-diode-netbox-plugin
  docker/docker-compose.yaml
  netbox_diode_plugin/api/serializers.py
Labels: markdown, python

#22 🚚 release: v0.3.0
  README.md
  docker/Dockerfile-diode-netbox-plugin
  docker/docker-compose.yaml
  netbox_diode_plugin/api/serializers.py
Labels: markdown, python

#23 fix: readme - compatibility plugin version
  README.md
Labels: markdown

#24 🚚 release: v0.4.1
  README.md
Labels: markdown

#25 feat: settings and ingestion logs views (init)
  Makefile
  docker/Dockerfile-diode-netbox-plugin
  docker/docker-compose.test.yaml
  docker/docker-compose.yaml
  docker/netbox/launch-netbox.sh
  docker/netbox/plugins_test.py
  docker/requirements-diode-netbox-plugin.txt
  netbox_diode_plugin/api/serializers.py
  netbox_diode_plugin/forms.py
  netbox_diode_plugin/migrations/0002_setting.py
  netbox_diode_plugin/models.py
  netbox_diode_plugin/navigation.py
  netbox_diode_plugin/reconciler/__init__.py
  netbox_diode_plugin/reconciler/sdk/__init__.py
  netbox_diode_plugin/reconciler/sdk/client.py
  netbox_diode_plugin/reconciler/sdk/exceptions.py
  netbox_diode_plugin/reconciler/sdk/v1/__init__.py
  netbox_diode_plugin/reconciler/sdk/v1/ingester_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/ingester_pb2.pyi
  netbox_diode_plugin/reconciler/sdk/v1/ingester_pb2_grpc.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.pyi
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2_grpc.py
  netbox_diode_plugin/reconciler/sdk/validate/__init__.py
  netbox_diode_plugin/reconciler/sdk/validate/validate_pb2.py
  netbox_diode_plugin/reconciler/sdk/validate/validate_pb2.pyi
  netbox_diode_plugin/reconciler/sdk/validate/validate_pb2_grpc.py
  netbox_diode_plugin/templates/diode/display_state.html
  netbox_diode_plugin/templates/diode/ingestion_logs.html
  netbox_diode_plugin/templates/diode/settings.html
  netbox_diode_plugin/templates/diode/settings_edit.html
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_object_state.py
  netbox_diode_plugin/tests/test_api_serializers.py
  netbox_diode_plugin/tests/test_models.py
  netbox_diode_plugin/tests/test_reconciler_sdk_client.py
  netbox_diode_plugin/tests/test_version.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/urls.py
  netbox_diode_plugin/views.py
  pyproject.toml
Labels: dependencies, python, internal

#26 feat: ingestion logs with pagination and metrics
  netbox_diode_plugin/navigation.py
  netbox_diode_plugin/reconciler/sdk/client.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.pyi
  netbox_diode_plugin/tables.py
  netbox_diode_plugin/templates/diode/ingestion_logs.html
  netbox_diode_plugin/templates/diode/ingestion_logs_paginator.html
  netbox_diode_plugin/templates/diode/ingestion_logs_table.html
  netbox_diode_plugin/templatetags/__init__.py
  netbox_diode_plugin/templatetags/diode_filters.py
  netbox_diode_plugin/tests/test_tables.py
  netbox_diode_plugin/tests/test_templatetags.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/views.py
Labels: python

#27 feat: ingestion logs with metrics improvements
  netbox_diode_plugin/tables.py
  netbox_diode_plugin/templates/diode/ingestion_logs.html
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/views.py
Labels: python

#29 feat: settings - rename reconciler target to diode target
  netbox_diode_plugin/api/serializers.py
  netbox_diode_plugin/forms.py
  netbox_diode_plugin/migrations/0002_setting.py
  netbox_diode_plugin/models.py
  netbox_diode_plugin/reconciler/sdk/client.py
  netbox_diode_plugin/templates/diode/settings.html
  netbox_diode_plugin/tests/test_models.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/views.py
Labels: python

#30 feat: plugin configuration improvements
  README.md
  docker/netbox/configuration/plugins.py
  netbox_diode_plugin/forms.py
  netbox_diode_plugin/migrations/0001_initial.py
  netbox_diode_plugin/migrations/0002_setting.py
  netbox_diode_plugin/tests/test_forms.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/views.py
Labels: markdown, python

#28 feat: store changeset into ingestion logs
  docker/requirements-diode-netbox-plugin.txt
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.pyi
  netbox_diode_plugin/templates/diode/ingestion_logs_table.html
  netbox_diode_plugin/templatetags/diode_filters.py
  netbox_diode_plugin/tests/test_templatetags.py
  pyproject.toml
Labels: dependencies, python

#32 feat: ingestion log state queued
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.pyi
  netbox_diode_plugin/templates/diode/ingestion_logs.html
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/views.py
Labels: python

#34 feat: plugin configuration further improvements
  README.md
  docker/netbox/configuration/plugins.py
  netbox_diode_plugin/__init__.py
  netbox_diode_plugin/forms.py
  netbox_diode_plugin/migrations/0001_initial.py
  netbox_diode_plugin/migrations/0002_setting.py
  netbox_diode_plugin/migrations/0003_clear_permissions.py
  netbox_diode_plugin/migrations/0004_rename_legacy_users.py
  netbox_diode_plugin/plugin_config.py
  netbox_diode_plugin/templates/diode/ingestion_logs.html
  netbox_diode_plugin/templates/diode/settings.html
  netbox_diode_plugin/tests/test_forms.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/views.py
Labels: markdown, python

#35 🚚 release
  Makefile
  README.md
  docker/Dockerfile-diode-netbox-plugin
  docker/docker-compose.test.yaml
  docker/docker-compose.yaml
  docker/netbox/configuration/plugins.py
  docker/netbox/launch-netbox.sh
  docker/netbox/plugins_test.py
  docker/requirements-diode-netbox-plugin.txt
  netbox_diode_plugin/__init__.py
  netbox_diode_plugin/api/serializers.py
  netbox_diode_plugin/forms.py
  netbox_diode_plugin/migrations/0001_initial.py
  netbox_diode_plugin/migrations/0002_setting.py
  netbox_diode_plugin/migrations/0003_clear_permissions.py
  netbox_diode_plugin/migrations/0004_rename_legacy_users.py
  netbox_diode_plugin/models.py
  netbox_diode_plugin/navigation.py
  netbox_diode_plugin/plugin_config.py
  netbox_diode_plugin/reconciler/__init__.py
  netbox_diode_plugin/reconciler/sdk/__init__.py
  netbox_diode_plugin/reconciler/sdk/client.py
  netbox_diode_plugin/reconciler/sdk/exceptions.py
  netbox_diode_plugin/reconciler/sdk/v1/__init__.py
  netbox_diode_plugin/reconciler/sdk/v1/ingester_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/ingester_pb2.pyi
  netbox_diode_plugin/reconciler/sdk/v1/ingester_pb2_grpc.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.py
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2.pyi
  netbox_diode_plugin/reconciler/sdk/v1/reconciler_pb2_grpc.py
  netbox_diode_plugin/reconciler/sdk/validate/__init__.py
  netbox_diode_plugin/reconciler/sdk/validate/validate_pb2.py
  netbox_diode_plugin/reconciler/sdk/validate/validate_pb2.pyi
  netbox_diode_plugin/reconciler/sdk/validate/validate_pb2_grpc.py
  netbox_diode_plugin/tables.py
  netbox_diode_plugin/templates/diode/display_state.html
  netbox_diode_plugin/templates/diode/ingestion_logs.html
  netbox_diode_plugin/templates/diode/ingestion_logs_paginator.html
  netbox_diode_plugin/templates/diode/ingestion_logs_table.html
  netbox_diode_plugin/templates/diode/settings.html
  netbox_diode_plugin/templates/diode/settings_edit.html
  netbox_diode_plugin/templatetags/__init__.py
  netbox_diode_plugin/templatetags/diode_filters.py
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_object_state.py
  netbox_diode_plugin/tests/test_api_serializers.py
  netbox_diode_plugin/tests/test_forms.py
  netbox_diode_plugin/tests/test_models.py
  netbox_diode_plugin/tests/test_reconciler_sdk_client.py
  netbox_diode_plugin/tests/test_tables.py
  netbox_diode_plugin/tests/test_templatetags.py
  netbox_diode_plugin/tests/test_version.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/urls.py
  netbox_diode_plugin/views.py
  pyproject.toml
Labels: markdown, dependencies, python, internal

#36 chore: README cleanup
  README.md
Labels: markdown

#37 fix: revoke superuser status from all diode users
  netbox_diode_plugin/migrations/0001_initial.py
  netbox_diode_plugin/migrations/0005_revoke_superuser_status.py
Labels: python

#38 🚚 release
  README.md
  netbox_diode_plugin/migrations/0001_initial.py
  netbox_diode_plugin/migrations/0005_revoke_superuser_status.py
Labels: markdown, python
