Repository netboxlabs/diode-netbox-plugin, pull requests merged in 2024-07, with the labels that each got.

#10 Update README.md
  README.md
Labels: markdown

#11 Update README.md
  README.md
Labels: markdown

#12 feat: rename INGESTION_API_KEY to DIODE_API_KEY
  README.md
  docker/netbox/env/netbox.env
  netbox_diode_plugin/management/commands/configurediodeplugin.py
Labels: markdown, python

#13 🚚 release
  README.md
  docker/netbox/env/netbox.env
  netbox_diode_plugin/management/commands/configurediodeplugin.py
Labels: markdown, python

#15 fix: ObjectStateView failing for IP address
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/tests/test_object_state.py
Labels: python

#16 🚚 release
  .github/workflows/lint-tests.yml
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/tests/test_object_state.py
Labels: python, github-actions
