Repository netboxlabs/diode-netbox-plugin, pull requests merged in 2025-04, with the labels that each got.

#68 fix: support for post create updates eg (primary mac address)
  docker/netbox/configuration/configuration.py
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/plugin_utils.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
  netbox_diode_plugin/tests/test_api_object_state.py
  pyproject.toml
Labels: dependencies, python

#69 Change set validation
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/serializers.py
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_serializers.py
Labels: python

#70 fix: expand support for cycle breaking, add additional logical matchers
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python

#71 fix: fix error fingerprinting tags
  Makefile
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python, internal

#73 feat: update data model
  Makefile
  docker/netbox/configuration/configuration.py
  docker/netbox/env/netbox.env
  docker/netbox/local_settings.py
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/plugin_utils.py
  netbox_diode_plugin/api/serializers.py
  netbox_diode_plugin/api/supported_models.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/api/urls.py
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
  netbox_diode_plugin/tests/test_api_object_state.py
  netbox_diode_plugin/tests/test_api_serializers.py
  pyproject.toml
Labels: dependencies, python, internal

#74 fix: adjust result structure
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
Labels: python

#76 fix: fix errors with harmonizing values
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python

#77 fix: merge tags rather than overwrite
  Makefile
  docker/netbox/configuration/logging.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python, internal

#78 fix: accept both valid forms of protoJSON (camelCase and snake_case)
  netbox_diode_plugin/api/plugin_utils.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
Labels: python

#80 fix: add special format transformations
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/plugin_utils.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python

#81 fix: special cases for ip network defaulting
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/plugin_utils.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python

#82 fix: fix complex vm interface update case
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: python

#83 fix: fix decimal and eui previous values
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
Labels: dependencies, python, github-actions, internal

#84 chore: update dependency versions to allow for newer releases
  pyproject.toml
Labels: dependencies

#87 fix: create and fix failing tests
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/common.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
  netbox_diode_plugin/tests/test_updates.py
  netbox_diode_plugin/tests/test_updates_cases.json
Labels: python

#86 feat: implement OAuth2 authentication and permissions
  README.md
  docker/netbox/env/netbox.env
  docker/netbox/plugins_dev.py
  netbox-plugin.yaml
  netbox_diode_plugin/__init__.py
  netbox_diode_plugin/api/__init__.py
  netbox_diode_plugin/api/applier.py
  netbox_diode_plugin/api/authentication.py
  netbox_diode_plugin/api/differ.py
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/api/permissions.py
  netbox_diode_plugin/api/plugin_utils.py
  netbox_diode_plugin/api/serializers.py
  netbox_diode_plugin/api/transformer.py
  netbox_diode_plugin/api/urls.py
  netbox_diode_plugin/api/views.py
  netbox_diode_plugin/forms.py
  netbox_diode_plugin/migrations/0001_initial.py
  netbox_diode_plugin/migrations/0001_squashed_0005.py
  netbox_diode_plugin/migrations/0003_clear_permissions.py
  netbox_diode_plugin/migrations/0004_rename_legacy_users.py
  netbox_diode_plugin/migrations/0005_revoke_superuser_status.py
  netbox_diode_plugin/migrations/__init__.py
  netbox_diode_plugin/models.py
  netbox_diode_plugin/navigation.py
  netbox_diode_plugin/plugin_config.py
  netbox_diode_plugin/search.py
  netbox_diode_plugin/templates/diode/settings.html
  netbox_diode_plugin/templates/diode/setup.html
  netbox_diode_plugin/tests/__init__.py
  netbox_diode_plugin/tests/test_api_apply_change_set.py
  netbox_diode_plugin/tests/test_api_diff_and_apply.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
  netbox_diode_plugin/tests/test_authentication.py
  netbox_diode_plugin/tests/test_forms.py
  netbox_diode_plugin/tests/test_models.py
  netbox_diode_plugin/tests/test_plugin_config.py
  netbox_diode_plugin/tests/test_updates.py
  netbox_diode_plugin/tests/test_version.py
  netbox_diode_plugin/tests/test_views.py
  netbox_diode_plugin/urls.py
  netbox_diode_plugin/version.py
  netbox_diode_plugin/views.py
Labels: markdown, python

#91 fix: consider object type in fingerprint all deduplication
  netbox_diode_plugin/api/matcher.py
  netbox_diode_plugin/tests/test_api_generate_diff.py
Labels: python

#93 fix: apply fails to create already existing object
  netbox_diode_plugin/api/applier.py
Labels: python

#94 chore: create tests for double created objects
  netbox_diode_plugin/tests/test_api_apply_change_set.py
Labels: python

#98 fix: GHA release clean up
  .github/workflows/release.yaml
Labels: github-actions

#99 🚀 release: 1.0.0
  .github/workflows/release.yaml
Labels: github-actions
